---
title: "LaTeX Table Tests"
author: "Benjamin Nutter"
date: "October 1, 2015"
output: 
  pdf_document: 
    keep_tex: yes
header-includes:
 - \usepackage{longtable}
 - \usepackage[dvipsnames,table]{xcolor}
 - \usepackage{array}
 - \usepackage{arydshln}
 - \usepackage{amssymb}
 - \usepackage{graphicx}
 - \makeatletter
 - \newcommand*\vdashline{\rotatebox[origin=c]{90}{$\dabar@\dabar@\dabar@$}}
 - \makeatother
---

```{r, echo = FALSE}
library(dplyr)
library(pixiedust)

mtcars2 <- mtcars[1:10, 1:4]

Hmisc::label(mtcars2$mpg) <- "Gas Mileage"
Hmisc::label(mtcars2$cyl) <- "Cylinders"
Hmisc::label(mtcars2$disp) <- "Displacement"
Hmisc::label(mtcars2$hp) <- "Horse Power"
# Hmisc::label(mtcars2$drat) <- "Rear Axle Ratio"
# Hmisc::label(mtcars2$wt) <- "Weight"
# Hmisc::label(mtcars2$qsec) <- "1/4 mile time"
# Hmisc::label(mtcars2$vs) <- "V/S"
# Hmisc::label(mtcars2$am) <- "Transmission"
# Hmisc::label(mtcars2$gear) <- "Forward Gears"
# Hmisc::label(mtcars2$carb) <- "Carburetors"

custom_head <- rbind(names(mtcars2), Hmisc::label(mtcars2)) %>%
  cbind(c("", ""), .) %>%
  as.data.frame(stringsAsFactors = FALSE) 
  

custom_foot <- rbind(vapply(mtcars2, mean, numeric(1)),
                     vapply(mtcars2, sd, numeric(1))) %>%
  cbind(c("", ""), .) %>%
  as.data.frame(stringsAsFactors = FALSE) 

custom_interfoot <- data.frame("To Be Continued", 
                               "", "", "", "")
```

```{r}
(x <- dust(mtcars2, keep_rownames = TRUE) %>%
  redust(custom_head, part = "head") %>%
  redust(custom_foot, part = "foot") %>%
  sprinkle(bg = "gray", part = "head") %>%
  sprinkle(bg = "lightgray", part = "foot") %>%
  sprinkle(rows = 2:3, cols = 3:4, 
           font_color = "Blue", 
           bold = TRUE, italic = TRUE,
           halign = "left", 
           font_size = 20) %>%
  sprinkle(rows = 2:3, border = "top") %>%
  # sprinkle(cols = 3, border = c("left", "right"), border_style = "dashed", border_color = "Red") %>%
  sprinkle(rows = 7, border = c("top", "bottom"), border_color = "Red") %>%
  sprinkle_table(round = 2) %>%
  sprinkle_print_method("latex"))
```

