---
title: "Advanced Magic with `pixiedust`"
author: "Benjamin Nutter"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: no
    number_section: yes
    toc: yes
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Advanced Magic with pixiedust}
  \usepackage[utf8]{inputenc}
---

The base table we will work with is defined by the following.

```{r, warning=FALSE, message = FALSE}
library(pixiedust)
inter <- data.frame("To", "Be", "Con", "tin", "ued",
                    "", "", "", "", "", "")
foot <- as.data.frame(lapply(mtcars, sum))

x <- dust(mtcars[1:10, ]) %>% 
  redust(foot, part = "foot") %>%
  redust(inter, part = "interfoot") %>%
  sprinkle(bg = "gray", part = "head") %>%
  sprinkle(bg = "lightgray", part = "foot")
```

# Console Output

## Longtable Feature

```{r}
x %>%
  sprinkle(longtable = 4)
```


# HTML Output

## Longtable Feature


```{r}
x %>%
  sprinkle(longtable = 4) %>%
  sprinkle_print_method("html")
```


# Markdown Output

## Longtable Feature
```{r}
x %>%
  sprinkle(longtable = 4) %>%
  sprinkle_print_method("markdown")
```