---
title: "`dustpan` Demonstration"
author: "Benjamin Nutter"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: no
    number_section: yes
    toc: yes
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{dustpan Demonstration}
  \usepackage[utf8]{inputenc}
---

```{r}
fit <- lm(mpg ~ qsec + factor(am), data = mtcars)
```

```{r}
fit
```

```{r}
summary(fit)
```

```{r}
library(broom)
tidy(fit)
```

```{r}
library(dustpan)
dust(fit)
```

```{r}
dust(fit) + 
  dust_round(colname = c("estimate", "statistic", "std.error"), round = 3) + 
  dust_fn(colname = "p.value", fn = quote(pvalString(value))) + 
  dust_colnames("Term", "Estimate", "SE", "T statistic", "p-value")
```

```{r}
dust(fit) + 
  dust_round(colname = c("estimate", "statistic", "std.error"), round = 3) + 
  dust_fn(colname = "p.value", fn = quote(pvalString(value))) + 
  dust_colnames("Term", "Estimate", "SE", "T statistic", "p-value") + 
  dust_bold(colname = "estimate", row = 2, set_bold=TRUE)
```

```{r}
dust(fit) + 
  dust_round(colname = c("estimate", "statistic", "std.error"), round = 3) + 
  dust_fn(colname = "p.value", fn = quote(pvalString(value))) + 
  dust_colnames("Term", "Estimate", "SE", "T statistic", "p-value") + 
  dust_bold(colname = "estimate", row = 2, set_bold=TRUE) + 
  dust_italic(colname = "estimate", row = 2:3, set_italic = TRUE) + 
  dust_head_halign(estimate = "r", statistic = "c", p.value = "left") + 
  dust_cell_halign(row=2, halign = "r") + 
  dust_print_method("html")
```

```{r}
dust(fit) + 
  dust_bg_pattern() + 
  dust_print_method("html")
```

```{r}
dust(fit) + 
  dust_round(colname = c("estimate", "statistic", "std.error"), round = 3) + 
  dust_fn(colname = "p.value", fn = quote(pvalString(value))) + 
  dust_cell_height(col = 2:4, height = 50) +
  dust_cell_valign(col = 2, valign = "t") + 
  dust_cell_valign(col = 3, valign = "m") + 
  dust_cell_valign(col = 4, valign = "b") + 
  dust_table_border("top", thickness = 3, color = "blue") + 
  dust_table_border(c("right", "left"), thickness = 2, units="px",
                    color = "red", style = "dotted") + 
  dust_cell_border(row = 1, col = c(2, 4), sides = c("top", "left"),
                   thickness = 2, color = "purple", style = "dotted") + 
  dust_print_method("html")
```