---
title: "`pixiedust` Supplemental Documentation"
author: "Benjamin Nutter"
date: '`r Sys.Date()`'
output: html_document
---

While I try to keep the documentation for `pixiedust` up-to-date and useful, it is sometimes difficult to understand the true implications of some of the sprinkles on different report formats.  The purpose of the supplemental documentation is to augment the package documentation with visual representations that aren't possible in the standard R documentation.  (Vignettes would be useful here, but the process of making vignettes for every output type and sprinkle would be cumbersome and bloat the package files).

If there are examples in topics you are particularly interested in, please [file an issue](https://github.com/nutterb/pixiedust/issues).  I'll work on updating this site as time permits.

## Medleys

Medleys are functions that consist of a collection of `sprinkles` in order to quickly and efficiently apply customizations to a table.  They are akin to `theme`s in `ggplot2`.

`pixiedust` ships with two medleys--`medley_bw`, and `medley_model`.  These medleys are really only examples.  I haven't tried to define a collection of "standardized" medleys, mostly because I have no idea what a "standardized" format might look like.  If you have ideas for medleys that would fit the general interest, please let me know.

[Appearance of `medley_bw`](medley-appearance-medley-bw.html)

## Sprinkles

## Multiple Tables